version: "3"

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "6501:5432"
    environment:
      POSTGRES_PASSWORD: asopos10
      POSTGRES_USER: postgres
      POSTGRES_DB: test_shop
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
