# Generated by Django 3.2.7 on 2023-11-27 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0004_alter_paymentinvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 11, 55, 36, 706815, tzinfo=utc), verbose_name='ΗΜΕΡΟΜΗΝΙΑ'),
        ),
    ]
