# Generated by Django 3.0.1 on 2020-12-04 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0026_auto_20200309_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 9, 47, 0, 458265, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
