# Generated by Django 3.0.1 on 2021-01-09 11:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0028_auto_20210109_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Κλειδωμενο'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Νέο'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Προηγούμενο'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='purpose_of_moving',
            field=models.CharField(blank=True, choices=[('a', 'ΠΩΛΗΣΗ'), ('b', 'ΛΙΑΝΙΚΗ')], max_length=1, null=True, verbose_name='Σκοπός Διακίνησης'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='loading_place',
            field=models.CharField(blank=True, default='Εδρα μας', max_length=240, null=True, verbose_name='Τόπος Φόρτωσης'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='transport',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Μεταφορικό Μέσο'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='costumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_invoices', to='costumers.Costumer', verbose_name='Πελάτης'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 11, 26, 52, 689104, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='order_type',
            field=models.CharField(choices=[('a', 'Τιμολογιο-Δελτίο Παραγγελίας'), ('b', 'Δελτίο Παραγγελίας'), ('c', 'Προπαραγγελία')], default='a', max_length=1, verbose_name='Ειδος Παραστατικου'),
        ),
    ]
