# Generated by Django 3.0.1 on 2021-01-09 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0029_auto_20210109_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Tιμη Πωλησης'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='taxes_modifier',
            field=models.CharField(choices=[('a', '6'), ('b', '13'), ('c', '24')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 12, 28, 57, 937722, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
