# Generated by Django 3.0.1 on 2021-01-11 15:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0030_auto_20210109_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='taxes_modifier',
            field=models.CharField(choices=[('a', '6'), ('b', '13'), ('c', '24')], default='c', max_length=1, verbose_name='ΦΠΑ'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 15, 43, 37, 29758, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='order_type',
            field=models.CharField(choices=[('a', 'Τιμολογιο-Δελτίο Αποστολής'), ('b', 'Δελτίο Παραγγελίας'), ('c', 'Προπαραγγελία')], default='a', max_length=1, verbose_name='Ειδος Παραστατικου'),
        ),
    ]
