# Generated by Django 3.0.1 on 2021-01-11 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0031_auto_20210111_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumerdetails',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='costumers.PaymentInvoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='costumers.PaymentInvoice'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 15, 47, 21, 981967, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='order_type',
            field=models.CharField(choices=[('a', 'Τιμολόγιο-Δελτίο Αποστολής'), ('b', 'Δελτίο Αποστολήε'), ('c', 'Προπαραγγελία')], default='a', max_length=1, verbose_name='Ειδος Παραστατικου'),
        ),
    ]
