# Generated by Django 3.0.1 on 2021-01-13 07:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200308_1104'),
        ('costumers', '0032_auto_20210111_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='Προϊον'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Περιγραφη'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='afm',
            field=models.CharField(blank=True, max_length=10, verbose_name='ΑΦΜ'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='Εδρα'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='doy',
            field=models.CharField(blank=True, max_length=150, verbose_name='ΔΟΥ'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='eponimia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Επωνυμια'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='fax',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='job',
            field=models.TextField(blank=True, verbose_name='Περιγραφη Επαγγελματος'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Τηλεφωνα'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='TK'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 7, 30, 37, 743216, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
