# Generated by Django 3.0.1 on 2021-01-14 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0033_auto_20210113_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='taxes_modifier',
            field=models.CharField(choices=[('1', '24'), ('2', '13'), ('3', '6'), ('4', '17'), ('5', '9'), ('6', '4'), ('7', '0')], default='c', max_length=1, verbose_name='ΦΠΑ'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('1', 'Τεμάχια'), ('1', 'Κιλά'), ('1', 'Λίτρα')], default='a', max_length=1, verbose_name='ΜΜ'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 6, 20, 6, 374887, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='order_type',
            field=models.CharField(choices=[('1.1', 'Τιμολόγιο Πώλησης'), ('2.1', 'Τιμολόγιο Παροχής')], default='a', max_length=3, verbose_name='Ειδος Παραστατικου'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='purpose_of_moving',
            field=models.CharField(blank=True, choices=[('1', 'Πώληση'), ('2', 'Πώληση για Λογαριασμό Τρίτων'), ('3', 'Δειγματισμός')], max_length=1, null=True, verbose_name='Σκοπός Διακίνησης'),
        ),
    ]
