# Generated by Django 3.0.1 on 2021-01-14 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0034_auto_20210114_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 6, 31, 6, 461757, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='payment_info',
            field=models.CharField(choices=[('1', 'Λογαριασμός Πληρωμών Ημεδαπής'), ('2', 'E-Banking Αρ. Λογ. Πάροχος Πληρωμών'), ('3', 'E-Pos Αρ. Λογ. Πάροχος Πληρωμών'), ('4', 'Κατάθεση Αρ. Λογ. Πάροχος Πληρωμών'), ('5', 'Λογαριασμός Πληρωμών Αλλοδαπής'), ('6', 'E-Banking Αρ. Λογ. Πάροχος Πληρωμών'), ('7', 'E-Pos Αρ. Λογ. Πάροχος Πληρωμών'), ('8', 'Κατάθεση Αρ. Λογ. Πάροχος Πληρωμών'), ('9', 'Μετρητά')], default='9', max_length=3),
        ),
    ]
