# Generated by Django 3.0.1 on 2021-01-15 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0035_auto_20210114_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='authenticationCode',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Συμβολοσειρά Αυθεντικοποίησης'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='mark',
            field=models.TextField(blank=True, null=True, verbose_name='Μοναδικός Αριθμός Καταχώρησης Παραστατικού'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='uid',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Αναγνωριστικό Παραστατικού'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 5, 31, 24, 610304, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
