# Generated by Django 3.0.1 on 2021-01-28 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200308_1104'),
        ('costumers', '0036_auto_20210115_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Προϊον'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 14, 44, 47, 772331, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='order_type',
            field=models.CharField(choices=[('1.1', 'Τιμολόγιο Πώλησης'), ('2.1', 'Τιμολόγιο Παροχής')], default=1.1, max_length=3, verbose_name='Ειδος Παραστατικου'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='purpose_of_moving',
            field=models.CharField(blank=True, choices=[('1', 'Πώληση'), ('2', 'Πώληση για Λογαριασμό Τρίτων'), ('3', 'Δειγματισμός')], default=1, max_length=1, null=True, verbose_name='Σκοπός Διακίνησης'),
        ),
    ]
