# Generated by Django 3.0.1 on 2021-02-05 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0037_auto_20210128_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('1', 'Τεμάχια'), ('2', 'Κιλά'), ('3', 'Λίτρα')], max_length=1, verbose_name='ΜΜ'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 5, 48, 25, 453496, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='order_type',
            field=models.CharField(choices=[('1.1', 'Τιμολόγιο - Δελτίο Αποστολής'), ('2.1', 'Τιμολόγιο Παροχής'), ('c', 'Προπαραγγελια')], default=1.1, max_length=3, verbose_name='Ειδος Παραστατικου'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='purpose_of_moving',
            field=models.CharField(blank=True, choices=[('1', 'Πώληση'), ('2', 'Πώληση για Λογαριασμό Τρίτων'), ('a', 'Δειγματισμός')], default=1, max_length=1, null=True, verbose_name='Σκοπός Διακίνησης'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='series',
            field=models.CharField(choices=[('a', 'A'), ('b', 'Δοκιμαστικο')], max_length=1, verbose_name='Σειρά'),
        ),
    ]
