# Generated by Django 3.0.1 on 2021-02-16 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0039_auto_20210205_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('1', 'Τεμάχια'), ('2', 'Κιλά'), ('3', 'Λίτρα')], default='1', max_length=1, verbose_name='ΜΜ'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 5, 32, 56, 559264, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
