# Generated by Django 3.0.1 on 2021-02-16 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0040_auto_20210216_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 5, 34, 12, 199557, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
