# Generated by Django 3.0.1 on 2021-02-16 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0042_auto_20210216_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 7, 29, 36, 55002, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='order_type',
            field=models.CharField(choices=[('1.1', 'Τιμολόγιο - Δελτίο Αποστολής'), ('2.1', 'Τιμολόγιο Παροχής'), ('c', 'Προπαραγγελια'), ('d', 'Δελτίο Αποστολής')], default=1.1, max_length=3, verbose_name='Ειδος Παραστατικου'),
        ),
    ]
