# Generated by Django 3.0.1 on 2021-02-16 08:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0043_auto_20210216_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 8, 9, 51, 246949, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
