# Generated by Django 3.0.1 on 2021-09-02 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0045_auto_20210528_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='amka',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ψευδονυμο'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 2, 6, 58, 58, 201107, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
