# Generated by Django 3.0.1 on 2022-02-04 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0046_auto_20210902_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 17, 20, 42, 679929, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
