# Generated by Django 3.0.1 on 2022-06-10 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0047_auto_20220204_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 9, 28, 7, 852054, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
