# Generated by Django 3.2.7 on 2023-02-08 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0048_auto_20220610_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 18, 40, 6, 680015, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
