# Generated by Django 3.2.7 on 2023-02-09 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0050_alter_paymentinvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 7, 12, 49, 326230, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
