# Generated by Django 3.2.7 on 2023-03-31 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0051_alter_paymentinvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 5, 40, 6, 95248, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
