# Generated by Django 3.2.7 on 2023-04-03 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0052_alter_paymentinvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 11, 7, 33, 565637, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
