# Generated by Django 3.2.7 on 2023-06-12 23:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0053_alter_paymentinvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 23, 29, 10, 614769, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
