# Generated by Django 3.2.7 on 2023-04-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_expenses', '0003_generalexpense_paid_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalexpense',
            name='taxes_13',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='ΠΟΣΟ ΦΠΑ 13%'),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='taxes_24',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='ΠΟΣΟ ΦΠΑ 24%'),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='taxes_6',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='ΠΟΣΟ ΦΠΑ 6%'),
        ),
    ]
