# Generated by Django 3.2.7 on 2023-06-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_expenses', '0004_auto_20230403_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalexpense',
            options={'ordering': ['-date']},
        ),
    ]
