# Generated by Django 3.2.7 on 2023-11-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxesModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.IntegerField(default=80, verbose_name='24%')),
                ('half', models.IntegerField(default=0, verbose_name='13%')),
                ('six', models.IntegerField(default=20, verbose_name='6%')),
            ],
        ),
    ]
