# Generated by Django 3.2.7 on 2023-11-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20231127_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['date', 'id']},
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνια'),
        ),
    ]
