# Generated by Django 3.0.1 on 2021-01-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_vendor_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['identifier', 'title']},
        ),
    ]
