# Generated by Django 3.0.1 on 2021-02-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_auto_20210109_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='taxes_modifier',
            field=models.CharField(choices=[('a', 0), ('d', 6), ('b', 13), ('c', 24)], default='c', max_length=1),
        ),
    ]
