# Generated by Django 3.0.1 on 2022-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_auto_20210216_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='ΕΠΑΓΓΕΛΜΑ'),
        ),
    ]
