# Generated by Django 3.0.1 on 2022-06-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_vendor_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('edited', models.DateField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=240, verbose_name='ΠΕΡΙΓΡΑΦΗ')),
                ('date', models.DateField(verbose_name='ΗΜΕΡΟΜΗΝΙΑ')),
                ('is_done', models.BooleanField(default=False, verbose_name='ΟΛΟΚΛΗΡΩΜΕΝΗ')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor', verbose_name='ΠΡΟΜΗΘΕΥΤΗΣ')),
            ],
        ),
    ]
