# Generated by Django 3.2.7 on 2023-02-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20230208_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='ΠΛΗΡΩΜΕΝΟ'),
        ),
    ]
