# Generated by Django 3.2.7 on 2023-11-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, verbose_name='Ονομασια')),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(choices=[('a', 'Τεμάχιο'), ('b', 'Κιβώτιο'), ('c', 'Κιλό')], default='a', max_length=1)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Ποσότητα')),
                ('safe_qty', models.IntegerField(default=0, null=True, verbose_name='Ελάχιστη ποσότητα')),
                ('price_buy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Τελευταία Τιμή Αγοράς')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Τιμή Πώλησης')),
                ('average_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Μεση Τιμή')),
                ('final_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes_modifier', models.CharField(blank=True, choices=[('a', 0), ('d', 6), ('b', 13), ('c', 24)], max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Προϊόν',
            },
        ),
        migrations.CreateModel(
            name='ProductVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Αγαπημένο')),
                ('sku', models.CharField(blank=True, max_length=150, verbose_name='Κωδικος Τιμολογιου')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αρχική Αξία')),
                ('discount', models.IntegerField(default=0, verbose_name='Εκπτωση')),
                ('clean_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Καθαρη Αξια')),
                ('taxes_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αξια μετα Φορους')),
                ('added_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Επιπλεον Αξια')),
                ('final_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Τελικη Αξια')),
                ('taxes_modifier', models.CharField(choices=[('a', 0), ('d', 6), ('b', 13), ('c', 24)], default='c', max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendors', to='products.product', verbose_name='Προϊον')),
            ],
            options={
                'ordering': ['-is_favorite', 'product__title'],
            },
        ),
    ]
