# Generated by Django 3.2.7 on 2023-11-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvendor',
            name='vendor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor', verbose_name='Προμηθευτης'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.Category', verbose_name='Κατηγορίες'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_list',
            field=models.ManyToManyField(blank=True, to='products.PriceList', verbose_name='prices_list'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendors',
            field=models.ManyToManyField(blank=True, through='products.ProductVendor', to='vendors.Vendor', verbose_name='Προμηθευτές'),
        ),
    ]
