# Generated by Django 3.2.7 on 2023-11-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_code',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
