# Generated by Django 3.2.7 on 2023-11-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='running_average_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Τρέχων Μεση Τιμή'),
        ),
    ]
