# Generated by Django 3.0.1 on 2021-02-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200308_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxes_modifier',
            field=models.CharField(blank=True, choices=[('a', 0), ('d', 6), ('b', 13), ('c', 24)], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='taxes_modifier',
            field=models.CharField(choices=[('a', 0), ('d', 6), ('b', 13), ('c', 24)], default='c', max_length=1),
        ),
    ]
