# Generated by Django 3.0.1 on 2021-02-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210216_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Ποσότητα'),
        ),
    ]
