# Generated by Django 3.2.7 on 2023-06-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20210216_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Τιμή/Μοναδα '),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Τιμή Έκπτωσης/Σακιου'),
        ),
    ]
