# Generated by Django 3.2.7 on 2023-06-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20230613_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Τιμή ανα Μοναδα '),
        ),
    ]
