# Generated by Django 3.2.7 on 2023-06-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20230617_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price_list',
            field=models.ManyToManyField(blank=True, to='products.PriceList', verbose_name='prices_list'),
        ),
    ]
